---
site_name: Certbot Deployer
site_dir: docs_output
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_private_members: false
            filters:
              # This regex filter will exclude members named `main`
              # even if they don’t start with an underscore.
              - '^(?!(main|parse_args|__.*__)$).*'
