---
site_name: Certbot Deployer
site_dir: docs_output
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_private_members: false
            filters:
              - '^(?!(main|parse_args|_.*|__.*__)$).*'
